// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 37.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'wedding_service_module';

  static const String assets_images_ads_image_1_jpeg = 'assets/images/ads_image_1.jpeg';
  static const String wedding_service_module$assets_images_ads_image_1_jpeg = 'packages/wedding_service_module/assets/images/ads_image_1.jpeg';

  static const String assets_images_ads_image_2_jpeg = 'assets/images/ads_image_2.jpeg';
  static const String wedding_service_module$assets_images_ads_image_2_jpeg = 'packages/wedding_service_module/assets/images/ads_image_2.jpeg';

  static const String assets_images_ads_image_3_jpeg = 'assets/images/ads_image_3.jpeg';
  static const String wedding_service_module$assets_images_ads_image_3_jpeg = 'packages/wedding_service_module/assets/images/ads_image_3.jpeg';

  static const String assets_images_ao_dai_ads_image_1_jpeg = 'assets/images/ao_dai_ads_image_1.jpeg';
  static const String wedding_service_module$assets_images_ao_dai_ads_image_1_jpeg = 'packages/wedding_service_module/assets/images/ao_dai_ads_image_1.jpeg';

  static const String assets_images_ao_dai_ads_image_2_jpeg = 'assets/images/ao_dai_ads_image_2.jpeg';
  static const String wedding_service_module$assets_images_ao_dai_ads_image_2_jpeg = 'packages/wedding_service_module/assets/images/ao_dai_ads_image_2.jpeg';

  static const String assets_images_ao_dai_ads_image_3_jpeg = 'assets/images/ao_dai_ads_image_3.jpeg';
  static const String wedding_service_module$assets_images_ao_dai_ads_image_3_jpeg = 'packages/wedding_service_module/assets/images/ao_dai_ads_image_3.jpeg';

  static const String assets_images_ao_dai_ads_image_4_jpeg = 'assets/images/ao_dai_ads_image_4.jpeg';
  static const String wedding_service_module$assets_images_ao_dai_ads_image_4_jpeg = 'packages/wedding_service_module/assets/images/ao_dai_ads_image_4.jpeg';

  static const String assets_images_ao_dai_ct_ads_image_1_png = 'assets/images/ao_dai_ct_ads_image_1.png';
  static const String wedding_service_module$assets_images_ao_dai_ct_ads_image_1_png = 'packages/wedding_service_module/assets/images/ao_dai_ct_ads_image_1.png';

  static const String assets_images_ao_dai_ct_ads_image_2_jpeg = 'assets/images/ao_dai_ct_ads_image_2.jpeg';
  static const String wedding_service_module$assets_images_ao_dai_ct_ads_image_2_jpeg = 'packages/wedding_service_module/assets/images/ao_dai_ct_ads_image_2.jpeg';

  static const String assets_images_ao_dai_ct_ads_image_3_jpeg = 'assets/images/ao_dai_ct_ads_image_3.jpeg';
  static const String wedding_service_module$assets_images_ao_dai_ct_ads_image_3_jpeg = 'packages/wedding_service_module/assets/images/ao_dai_ct_ads_image_3.jpeg';

  static const String assets_images_car_ads_image_1_jpeg = 'assets/images/car_ads_image_1.jpeg';
  static const String wedding_service_module$assets_images_car_ads_image_1_jpeg = 'packages/wedding_service_module/assets/images/car_ads_image_1.jpeg';

  static const String assets_images_car_ads_image_2_jpeg = 'assets/images/car_ads_image_2.jpeg';
  static const String wedding_service_module$assets_images_car_ads_image_2_jpeg = 'packages/wedding_service_module/assets/images/car_ads_image_2.jpeg';

  static const String assets_images_car_ads_image_3_jpeg = 'assets/images/car_ads_image_3.jpeg';
  static const String wedding_service_module$assets_images_car_ads_image_3_jpeg = 'packages/wedding_service_module/assets/images/car_ads_image_3.jpeg';

  static const String assets_images_car_ads_image_4_png = 'assets/images/car_ads_image_4.png';
  static const String wedding_service_module$assets_images_car_ads_image_4_png = 'packages/wedding_service_module/assets/images/car_ads_image_4.png';

  static const String assets_images_dress_ads_image_1_jpeg = 'assets/images/dress_ads_image_1.jpeg';
  static const String wedding_service_module$assets_images_dress_ads_image_1_jpeg = 'packages/wedding_service_module/assets/images/dress_ads_image_1.jpeg';

  static const String assets_images_dress_ads_image_2_jpeg = 'assets/images/dress_ads_image_2.jpeg';
  static const String wedding_service_module$assets_images_dress_ads_image_2_jpeg = 'packages/wedding_service_module/assets/images/dress_ads_image_2.jpeg';

  static const String assets_images_dress_ads_image_3_jpeg = 'assets/images/dress_ads_image_3.jpeg';
  static const String wedding_service_module$assets_images_dress_ads_image_3_jpeg = 'packages/wedding_service_module/assets/images/dress_ads_image_3.jpeg';

  static const String assets_images_dress_ads_image_4_jpeg = 'assets/images/dress_ads_image_4.jpeg';
  static const String wedding_service_module$assets_images_dress_ads_image_4_jpeg = 'packages/wedding_service_module/assets/images/dress_ads_image_4.jpeg';

  static const String assets_images_mc_ads_image_1_jpeg = 'assets/images/mc_ads_image_1.jpeg';
  static const String wedding_service_module$assets_images_mc_ads_image_1_jpeg = 'packages/wedding_service_module/assets/images/mc_ads_image_1.jpeg';

  static const String assets_images_restaurant_ads_image_1_jpeg = 'assets/images/restaurant_ads_image_1.jpeg';
  static const String wedding_service_module$assets_images_restaurant_ads_image_1_jpeg = 'packages/wedding_service_module/assets/images/restaurant_ads_image_1.jpeg';

  static const String assets_images_restaurant_ads_image_2_jpeg = 'assets/images/restaurant_ads_image_2.jpeg';
  static const String wedding_service_module$assets_images_restaurant_ads_image_2_jpeg = 'packages/wedding_service_module/assets/images/restaurant_ads_image_2.jpeg';

  static const String assets_images_restaurant_ads_image_3_png = 'assets/images/restaurant_ads_image_3.png';
  static const String wedding_service_module$assets_images_restaurant_ads_image_3_png = 'packages/wedding_service_module/assets/images/restaurant_ads_image_3.png';

  static const String assets_images_restaurant_ads_image_4_jpeg = 'assets/images/restaurant_ads_image_4.jpeg';
  static const String wedding_service_module$assets_images_restaurant_ads_image_4_jpeg = 'packages/wedding_service_module/assets/images/restaurant_ads_image_4.jpeg';

  static const String assets_images_trang_diem_ads_image_1_jpeg = 'assets/images/trang_diem_ads_image_1.jpeg';
  static const String wedding_service_module$assets_images_trang_diem_ads_image_1_jpeg = 'packages/wedding_service_module/assets/images/trang_diem_ads_image_1.jpeg';

  static const String assets_images_trang_diem_ads_image_2_jpeg = 'assets/images/trang_diem_ads_image_2.jpeg';
  static const String wedding_service_module$assets_images_trang_diem_ads_image_2_jpeg = 'packages/wedding_service_module/assets/images/trang_diem_ads_image_2.jpeg';

  static const String assets_images_trang_diem_ads_image_3_jpeg = 'assets/images/trang_diem_ads_image_3.jpeg';
  static const String wedding_service_module$assets_images_trang_diem_ads_image_3_jpeg = 'packages/wedding_service_module/assets/images/trang_diem_ads_image_3.jpeg';

  static const String assets_images_trang_diem_ads_image_4_jpeg = 'assets/images/trang_diem_ads_image_4.jpeg';
  static const String wedding_service_module$assets_images_trang_diem_ads_image_4_jpeg = 'packages/wedding_service_module/assets/images/trang_diem_ads_image_4.jpeg';

  static const String assets_images_trap_ads_image_1_jpeg = 'assets/images/trap_ads_image_1.jpeg';
  static const String wedding_service_module$assets_images_trap_ads_image_1_jpeg = 'packages/wedding_service_module/assets/images/trap_ads_image_1.jpeg';

  static const String assets_images_trap_ads_image_2_jpeg = 'assets/images/trap_ads_image_2.jpeg';
  static const String wedding_service_module$assets_images_trap_ads_image_2_jpeg = 'packages/wedding_service_module/assets/images/trap_ads_image_2.jpeg';

  static const String assets_images_trap_ads_image_3_jpeg = 'assets/images/trap_ads_image_3.jpeg';
  static const String wedding_service_module$assets_images_trap_ads_image_3_jpeg = 'packages/wedding_service_module/assets/images/trap_ads_image_3.jpeg';

  static const String assets_images_trap_ads_image_4_jpeg = 'assets/images/trap_ads_image_4.jpeg';
  static const String wedding_service_module$assets_images_trap_ads_image_4_jpeg = 'packages/wedding_service_module/assets/images/trap_ads_image_4.jpeg';

  static const String assets_images_vest_ads_image_1_jpeg = 'assets/images/vest_ads_image_1.jpeg';
  static const String wedding_service_module$assets_images_vest_ads_image_1_jpeg = 'packages/wedding_service_module/assets/images/vest_ads_image_1.jpeg';

  static const String assets_images_vest_ads_image_2_jpeg = 'assets/images/vest_ads_image_2.jpeg';
  static const String wedding_service_module$assets_images_vest_ads_image_2_jpeg = 'packages/wedding_service_module/assets/images/vest_ads_image_2.jpeg';

  static const String assets_images_vest_ads_image_3_jpeg = 'assets/images/vest_ads_image_3.jpeg';
  static const String wedding_service_module$assets_images_vest_ads_image_3_jpeg = 'packages/wedding_service_module/assets/images/vest_ads_image_3.jpeg';

  static const String assets_images_viet_phuc_ads_image_1_jpeg = 'assets/images/viet_phuc_ads_image_1.jpeg';
  static const String wedding_service_module$assets_images_viet_phuc_ads_image_1_jpeg = 'packages/wedding_service_module/assets/images/viet_phuc_ads_image_1.jpeg';

  static const String assets_images_viet_phuc_ads_image_2_jpeg = 'assets/images/viet_phuc_ads_image_2.jpeg';
  static const String wedding_service_module$assets_images_viet_phuc_ads_image_2_jpeg = 'packages/wedding_service_module/assets/images/viet_phuc_ads_image_2.jpeg';

  static const String assets_images_viet_phuc_ads_image_3_jpeg = 'assets/images/viet_phuc_ads_image_3.jpeg';
  static const String wedding_service_module$assets_images_viet_phuc_ads_image_3_jpeg = 'packages/wedding_service_module/assets/images/viet_phuc_ads_image_3.jpeg';
}
